Kért javítások #43
csngebnc/UnderSea pull request #47
Opened 2021-06-30 12:39 UTC by csngebnc

2021-06-30 12:57 UTC, koppa96 requested changes
https://github.com/csngebnc/UnderSea/blob/backend-fixes/backend/UnderSea.Api/SignalR/RoundHub.cs

Ehhez a fájlhoz nem tudtam kommentelni mert nem volt benne change. A namespacet fixeljétek.

2021-06-30 12:57 UTC, koppa96 commented on backend/UnderSea.Api/Controllers/CountryController.cs
> +        [HttpGet("country-name")]
Elég lenne így a HttpGet("name"), mert úgy api/country/name lesz a path

2021-06-30 12:57 UTC, koppa96 commented on backend/UnderSea.Api/Controllers/CountryController.cs
> +        [HttpPut("new-country-name")]
Ez is lehetne HttpPut("name"), ha már az ország nevét így egy erőforrásnak tekintjük.

2021-06-30 12:57 UTC, koppa96 commented on backend/UnderSea.Api/Controllers/RoundController.cs
> +        [HttpGet("call-next-round")]
Ez ne Get legyen, a Get egy idempotens HTTP ige. A Wikipédia szerint: "Idempotensnek azokat a metódusokat nevezzük, melyeknek többszöri végrehajtása ugyanazt a hatást váltja ki, mint az egyszeri." Nyilván ez a végpontra nem igaz.

2021-06-30 12:57 UTC, koppa96 commented on backend/UnderSea.Api/Program.cs
> +                .MigrateDatabase<UnderSeaDbContext>()
Ez szexi, nem is gondoltam még rá hogy lehetne extension method.

2021-06-30 12:57 UTC, koppa96 commented on backend/UnderSea.Api/Startup.cs
> +                    builder.WithOrigins(Configuration.GetSection("AllowedOrigins").Get<string[]>())
Cép

2021-06-30 12:57 UTC, koppa96 commented on backend/UnderSea.Api/Startup.cs
> +            builder.RegisterAssemblyTypes(Assembly.Load("UnderSea.Bll"))
😍

2021-06-30 12:57 UTC, koppa96 commented on backend/UnderSea.Bll/Services/BattleService.cs
>                  {
Ez itt lehetne egy Select, nem?

2021-06-30 12:57 UTC, koppa96 commented on backend/UnderSea.Bll/Services/BattleService.cs
>          {
Így már nem biztos hogy van értelme ennek külön függvényben léteznie

2021-06-30 12:57 UTC, koppa96 commented on backend/UnderSea.Bll/Services/RoundService.cs
> +        where THub : Hub
Ez még mindig illegális. 😄 Absztraháljátok el az IHubContextet a HttpContexthez hasonlóan, mint IIdentityServiceben

2021-06-30 12:59 UTC, koppa96 commented on backend/UnderSea.Api/Hosting/HostDataExtension.cs
> +        public static IHost MigrateDatabase<TContext>(this IHost host) where TContext : UnderSeaDbContext
Mi értelme van amúgy a TContext paraméternek ha megkötöd hogy UnderSeaDbContext legyen? Legyen csak DbContext a megkötés, így újrahasználhatóbb.

2021-06-30 13:07 UTC, surmannr commented on backend/UnderSea.Api/Program.cs
> +                .MigrateDatabase<UnderSeaDbContext>()
Gincsai kedvenc extension-je 😄

2021-06-30 13:15 UTC, csngebnc commented on backend/UnderSea.Api/Controllers/RoundController.cs
> +        [HttpGet("call-next-round")]
Post oké?

2021-06-30 21:06 UTC, koppa96 requested changes

2021-06-30 21:06 UTC, koppa96 commented on backend/UnderSea.Bll/Services/RoundService.cs
> +
Ide enged commentelni úgyhogy ideírom. A 268. sor még a 32 inches monitoromra se fér ki. 😄 Ezeket a hosszú sorokat tördeljétek.

2021-07-01 09:12 UTC, matemilan approved these changes

2021-07-01 09:27 UTC, koppa96 approved these changes

2021-07-01 09:29 UTC, merged